### ISSUE TITLE
sim8085 jz not working

### ISSUE THREAD

**Issue by himeshbhatia** [debjitbis08/sim8085#2]
jz instruction is neither highlighted nor able to be used.
used jnz and jmp instead, but please fix this bug.

;<Program title>

jmp start

;data

;code
start: nop
lda 0100h
mov b,a
lxi h,0101h
loop: mov a,m
inr a
inr a
inx h
mov m,a
dcr b
jz end
jmp loop

end: hlt

**Comment by debjitbis08** [comment]
Hi @himeshbhatia, 

Thanks for reporting this issue. I have fixed the underlying problem and your code seems to run fine. Note, that you need to enter some value at memory location `0x0100` for the loop to terminate.

Please check if the fix is working for you and let me know if you face this again.
