### ISSUE TITLE
Auxillary Carry

### ISSUE THREAD

**Issue by amanat-2003** [debjitbis08/sim8085#50]
Auxillary Carry not working properly when INR, DCR, ADI is used

**Comment by Hardik-Ahi** [comment]
The CMP instruction too seems to be wrongly setting the auxiliary carry flag when it should not be set.

Consider the attached example program that converts a given decimal number to hexadecimal.
Take the input value as '15', so the output should be '0F'. But it shows '35'.

Upon tracing, I found that for the operation (05 - 15) it is setting the auxiliary carry flag to 1, whereas it should be 0, because this operation does not require any borrow from the higher nibble.

[decimal-to-hex.txt](https://github.com/debjitbis08/sim8085/files/11950482/decimal-to-hex.txt)

**Comment by debjitbis08** [comment]
Fixed.
